export default function SvgDefs() {
  return (
    <svg width="0" height="0" viewBox="0 0 3316 1942">
      <defs>
        <image
          id="chomerce-account"
          width="1366"
          height="768"
          xlinkHref="/captures/chomerce/account.jpeg"
        />
        <image
          id="chomerce-home"
          width="1366"
          height="768"
          xlinkHref="/captures/chomerce/home.jpeg"
        />
        <image
          id="chomerce-cart"
          width="1366"
          height="768"
          xlinkHref="/captures/chomerce/cart.jpeg"
        />
        <image
          id="chomerce-admin"
          width="1366"
          height="768"
          xlinkHref="/captures/chomerce/admin.jpeg"
        />
        <image
          id="epb-login"
          width="1366"
          height="768"
          xlinkHref="/captures/epb/login.png"
        />
        <image
          id="epb-emb"
          width="1366"
          height="768"
          xlinkHref="/captures/epb/emb.png"
        />
        <image
          id="portfolio-home"
          width="1366"
          height="768"
          xlinkHref="/captures/portfolio/home.png"
        />
        <image
          id="portfolio-about"
          width="1366"
          height="768"
          xlinkHref="/captures/portfolio/about-me.png"
        />
        <image
          id="portfolio-education"
          width="1366"
          height="768"
          xlinkHref="/captures/portfolio/education.png"
        />
        <image
          id="portfolio-projects"
          width="1366"
          height="768"
          xlinkHref="/captures/portfolio/projects.png"
        />
        <image
          id="bmt-auth"
          width="1366"
          height="768"
          xlinkHref="/captures/bmt/auth.png"
        />
        <image
          id="bmt-dashboard"
          width="1366"
          height="768"
          xlinkHref="/captures/bmt/dashboard.png"
        />
        <image
          id="bmt-prediction"
          width="1366"
          height="768"
          xlinkHref="/captures/bmt/prediction.png"
        />
      </defs>
    </svg>
  );
}
